import {useState} from "react";
import {FlowCanvas} from "../features/canvas/FlowCanvas";
import {useGraphStore, importGraphJson, type NodeType} from "../features/canvas/graphStore";
import {RunHistory} from "../features/observability/RunHistory"; import {deleteRun} from "../features/observability/runApi"; import {TraceDrawer,type TraceEvent} from "../features/observability/TraceDrawer";
import {Inspector} from "../features/inspector/Inspector"; import {WorkspaceFiles} from "../features/inspector/WorkspaceFiles";
import {WsClient} from "../features/observability/wsClient";
import {requestProviderApproval} from "../features/inspector/approvalApi"; import {downloadGraph} from "../features/canvas/downloadGraph"; import {saveGraph} from "../features/canvas/graphApi"; import {runGraph} from "../features/canvas/runApi"; import {exportGraph} from "../features/export_bundle/exportApi";
import {useEffect} from "react"; import {getSessionToken,setSessionToken,clearSessionToken} from "../shared/session";
export function App(){
 const [error,setError]=useState<string|null>(null); const [events,setEvents]=useState<TraceEvent[]>([]); const {setGraph,reviewOnly,setReviewOnly,nodes,selectedNodeId,externalDataflowActivated,updateConfig}=useGraphStore();
 useEffect(()=>{useGraphStore.getState().recover(); const keydown=(event:KeyboardEvent)=>{const state=useGraphStore.getState();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();state.undo()}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="y"){event.preventDefault();state.redo()}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="d"){event.preventDefault();if(state.selectedNodeId)state.duplicateNode(state.selectedNodeId)}else if((event.key==="Delete"||event.key==="Backspace")&&state.selectedNodeId){event.preventDefault();state.deleteSelected()}};window.addEventListener("keydown",keydown); const client=new WsClient(`ws://${location.host}/ws`,getSessionToken(),event=>{setEvents(previous=>[...previous,{type:event.type,payload:event.payload||{}}].slice(-200)); const nodeId=event.payload?.node_id; if(typeof nodeId==="string"){const status=event.type.endsWith("running")||event.type.endsWith("queued")?"running":event.type.endsWith("succeeded")?"success":event.type.endsWith("failed")?"error":null;if(status)useGraphStore.getState().setNodeStatus(nodeId,status)}}); client.connect(); return ()=>{window.removeEventListener("keydown",keydown);client.close()};},[]);
 const add=(type:NodeType)=>{const id=`${type}-${Date.now()}`; const node={id,type,position:{x:100,y:100},data:{config:{},ui:{}}}; const state=useGraphStore.getState(); if(state.nodes.length>=50){setError("Node limit reached");return;} setGraph([...state.nodes,node],state.edges);};
 const token=()=>getSessionToken(); const payload=()=>({schema_version:"1" as const,id:"local",name:"Local graph",workspace_path:".",nodes,edges:useGraphStore.getState().edges,settings:{review_only:reviewOnly,external_dataflow_activated:externalDataflowActivated}}); const save=async()=>{try{await saveGraph("graph.forge.json",payload(),token());setError(null)}catch{setError("Save failed")}}; const run=async()=>{try{await runGraph(payload(),"",token());setError(null)}catch{setError("Run failed")}}; const exportBundle=async()=>{try{await exportGraph(payload(),"bundle",token());setError(null)}catch{setError("Export failed")}};
 const load=(raw:string)=>{try{const graph=importGraphJson(raw);setGraph(graph.nodes,graph.edges);setReviewOnly(true);setError(null);}catch(e){setError(e instanceof Error?e.message:"Invalid graph");}};
 return <main><header style={{padding:16}}><img src="/assets/logo.jpg" alt="HarnessForge logo" width="40" height="40" /> HarnessForge <strong>{reviewOnly?"Review mode":"Active"}</strong></header><nav aria-label="Node palette">{(["start","llm","rag","loop","reducer","tool","output"] as NodeType[]).map(type=><button key={type} onClick={()=>add(type)}>{type}</button>)}<button onClick={()=>setReviewOnly(!reviewOnly)}>{reviewOnly?"Activate":"Review"}</button><button onClick={save}>Save</button><button onClick={()=>downloadGraph(payload())}>Download JSON</button><button onClick={run} disabled={reviewOnly}>Run</button><button onClick={exportBundle} disabled={reviewOnly}>Export</button><label> Session token <input type="password" aria-label="session token" onChange={e=>{try{setSessionToken(e.target.value);setError(null)}catch{setError("Invalid session token")}}} /></label><button onClick={()=>{clearSessionToken();setError("Session cleared")}}>Clear session</button><label> Import <input type="file" accept=".json,.forge.json" onChange={e=>{const file=e.target.files?.[0];if(file)file.text().then(load);}} /></label></nav>{error&&<p role="alert">{error}</p>}<RunHistory token={token()} onSelect={id=>setError(`Selected run ${id}`)} onDelete={id=>{void deleteRun(id,token()).then(()=>setError(null)).catch(()=>setError("Delete failed"))}}/><WorkspaceFiles token={token()} onSelect={file=>setError(`Selected ${file}`)}/><Inspector node={nodes.find(node=>node.id===selectedNodeId)} onConfigChange={config=>{if(selectedNodeId)updateConfig(selectedNodeId,config)}} onActivateDataflow={()=>useGraphStore.getState().setExternalDataflow(true)} onRequestApproval={bindings=>{const node=nodes.find(item=>item.id===selectedNodeId);return requestProviderApproval((node?.data.config.provider as Record<string,unknown>)||{},bindings,token()).then(result=>result.approval_fingerprint)}}/><FlowCanvas/><TraceDrawer events={events} onClear={()=>setEvents([])}/></main>
}
